package huga721.github.spring.todo.app.model.repo;

import huga721.github.spring.todo.app.model.entities.Project;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
/**
 * All methods are generated by Spring
 * white list interface
 */
@Repository
public interface ProjectRepository{
    List<Project> findAll(); // Method to find all projects

    Optional<Project> findById(Integer id); // Method to find project by id

    Project save(Project entity); // Method to save object in db
}
