package huga721.github.spring.todo.app.model.repo;

import huga721.github.spring.todo.app.model.entities.TaskGroup;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
/**
 * All methods are generated by Spring
 * white list interface
 */
@Repository
public interface TaskGroupRepository {
    List<TaskGroup> findAll(); // Method to find all task group

    Optional<TaskGroup> findById(Integer id); // Method to find by id task group

    TaskGroup save(TaskGroup entity); // Method to save task group

    //Method to check if group of tasks is false
    boolean existsByDoneIsFalseAndProject_Id(Integer projectId);
}
