package huga721.github.spring.todo.app.model.repo;

import huga721.github.spring.todo.app.model.entities.Task;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;
/**
 * All methods are generated by Spring
 * white list interface
 */
@Repository
public interface TaskRepository {
    List<Task> findAll(); // Find all task

    Page<Task> findAll(Pageable page); // Find all task but with paging

    Optional<Task> findById(Integer id); // Find task by id

    boolean existsById(Integer id); // Check if task exist by id

    Task save(Task entity); // Save task to db

    List<Task> findByDone(@Param("state") boolean done); // Find task by done

    boolean existsByDoneIsFalseAndGroup_Id(Integer groupId); // Check if done is false
}

